version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=storefront
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    # networks:
    #   - api

  # storefront-api:
  #   build: .
  #   container_name: storefront-api
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   networks:
  #     - api
volumes:
  postgres:

# networks:
#   api:
#     driver: bridge
